### ISSUE TITLE
Creating and adding entries to data lists crashes the game

### ISSUE THREAD

**Issue by CreeperEntertain** [Sumeshi2/MCreator-Plugins#1]
When creating a list, it is not possible to create them with an initial size or set their size. This makes it impossible to add entries, as doing so causes Java to throw an out of bounds error which says that the list size is 0, no matter what. I tried adding entries to a data list and expanding it in what I believe to be every conceivable way, and nothing worked.
The procedure block for creating a list with an initial size simply does not exist. Same for data maps.

I'm using the latest version of the plugin on MCreator 2024.1, Forge 1.20.1.

Maybe I'm just doing it wrong, but I don't see any block that adds entries other than the one that adds it to an index, which won't work since the list does not have any indexes, nor does it add any.

**Comment by Wakaba2** [comment]
You can add data elements to a data list as follows.
![datalist](https://github.com/user-attachments/assets/6b758df8-1a4f-458b-8a00-714a8c960218)

**Comment by CreeperEntertain** [comment]
I did it like that, but it crashed my game and wrote that the index was out of bounds.

**Comment by Wakaba2** [comment]
Make sure the index meets the requirements: 0 <= index, index <= list size.
Attempting to add elements outside this range will cause a crash or other issues.

**Comment by CreeperEntertain** [comment]
I switched to another plugin for list handling since it also adds the ability to create classes with parameters using procedure blocks. You can close this, as yours has intended behaviour. I'd like to still request that you update the tutorial page for the plugin to teach about these details, since it's not obvious it'll just expand the list and create empty entries if you add entries to indexes outside the range.

I assumed so specifically because vector list can also be created with an initial size.

**Comment by Wakaba2** [comment]
The initial size is not the actual size of vector lists and maps.

**Comment by Wakaba2** [comment]
Vector lists are variable size but those use internally fixed-size arrays. For vector lists, the initial size refers to the size of the array.
On the other hand, vector maps use a hash table internally to store vectors. For vector maps, the initial size is a size of the hash tables.

**Comment by Wakaba2** [comment]
Vector lists use array lists, which internally regenerate the array to expand the array each time an element is added to the list. The initial size can avoid inefficient regenerating the array. The same goes for vector maps.
